### ISSUE TITLE
lighthouse bot succeeds even when minimum required threshold is not met

### ISSUE THREAD

**Issue by StudioSpindle** [GoogleChromeLabs/lighthousebot#62]
See the output table on: https://github.com/StudioSpindle/spindle.wtf/pull/7#issuecomment-492333770

The settings in Travis are set like this: https://github.com/StudioSpindle/spindle.wtf/blob/develop/.travis.yml

Is this a bug or is it a setting that is wrong?

**Comment by erezrokah** [comment]
@StudioSpindle I had a similar issue. I found out it takes some time until the `lighthousebot` account responds to the invitation to collaborate.

You can check this here:
![image](https://user-images.githubusercontent.com/26760571/61278565-15541400-a7bd-11e9-9f53-0bd31d09c0d3.png)

**Comment by EoinTraynor** [comment]
Until Lighthouse accepts the invitation to collaborate it does not have permission to fail a check. 
However, it will post a comment on your PR.
Here is the original issue [Issue 8](https://github.com/GoogleChromeLabs/lighthousebot/issues/8)

@erezrokah How long did you have to wait for acceptance? I requested collaboration 6 days ago.

**Comment by erezrokah** [comment]
@EoinTraynor I don't remember exactly. I think a couple of hours
