### ISSUE TITLE
Feature request: GitHub Actions support

### ISSUE THREAD

**Issue by bukhalo** [GoogleChromeLabs/lighthousebot#74]
Maybe use [CircleCI integration PR](https://github.com/GoogleChromeLabs/lighthousebot/pull/68) as start point for work?

**Comment by bukhalo** [comment]
Ref: https://github.com/GoogleChromeLabs/lighthousebot/issues/72

**Comment by bukhalo** [comment]
Ref: Another realisation for GitHub Actions https://github.com/treosh/lighthouse-ci-action

**Comment by evilsprut** [comment]
Not actual after https://github.com/GoogleChrome/lighthouse-ci
